# Generated by Django 4.0.2 on 2022-11-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='city')),
            ],
        ),
        migrations.CreateModel(
            name='CommonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='region')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='currency')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='ethnic')),
            ],
        ),
        migrations.CreateModel(
            name='LandMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='tourist')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('demonyms', models.CharField(max_length=255)),
                ('flag', models.ImageField(upload_to='flag')),
                ('timezone', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('culture', models.CharField(max_length=255)),
                ('independence_date', models.DateField()),
                ('political_history', models.CharField(max_length=255)),
                ('language', models.FileField(upload_to='language')),
                ('anthem', models.FileField(upload_to='anthem')),
                ('city', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mapo.city')),
                ('common_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapo.commonregion')),
                ('currency', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Mapo.currency')),
                ('ethnic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapo.ethnic')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapo.landmark')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mapo.tourist')),
            ],
        ),
    ]
