# Generated by Django 4.0.2 on 2022-11-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='common_region',
        ),
        migrations.RemoveField(
            model_name='country',
            name='title',
        ),
        migrations.AddField(
            model_name='country',
            name='spoken_language',
            field=models.FileField(blank=True, default='', null=True, upload_to='language'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.AddField(
            model_name='country',
            name='city',
            field=models.ManyToManyField(to='Mapo.City'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ManyToManyField(to='Mapo.Currency'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='ethnic_group',
        ),
        migrations.AddField(
            model_name='country',
            name='ethnic_group',
            field=models.ManyToManyField(to='Mapo.Ethnic'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='landmark',
        ),
        migrations.AddField(
            model_name='country',
            name='landmark',
            field=models.ManyToManyField(to='Mapo.LandMark'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='language',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tourist',
        ),
        migrations.AddField(
            model_name='country',
            name='tourist',
            field=models.ManyToManyField(to='Mapo.Tourist'),
        ),
        migrations.DeleteModel(
            name='CommonRegion',
        ),
        migrations.AddField(
            model_name='country',
            name='common_religion',
            field=models.ManyToManyField(to='Mapo.CommonReligion'),
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.ForeignKey(default='', null='', on_delete=django.db.models.deletion.CASCADE, to='Mapo.countryname'),
        ),
        migrations.AddField(
            model_name='country',
            name='culture',
            field=models.ManyToManyField(to='Mapo.Culture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='demonyms',
            field=models.ForeignKey(default='', null='', on_delete=django.db.models.deletion.CASCADE, to='Mapo.demonyms'),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ManyToManyField(to='Mapo.LanguageName'),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.ManyToManyField(to='Mapo.Timezone'),
        ),
    ]
