# Generated by Django 4.0.2 on 2022-12-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mapo', '0002_commonreligion_countryname_culture_demonyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='capital')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.ForeignKey(default='', null='', on_delete=django.db.models.deletion.CASCADE, to='Mapo.capitalname'),
        ),
    ]
