# Generated by Django 4.0.2 on 2022-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapo', '0003_capitalname_country_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='call_code',
            field=models.CharField(default='', max_length=255, null=''),
        ),
    ]
