# Generated by Django 4.0.2 on 2022-12-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapo', '0004_country_call_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='culture'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CountryName',
        ),
    ]
